import { supabase } from "./supabase";
import type { AiPick } from "../types";

// AI picks are generated by a Supabase Edge Function that calls the Claude API.
// Rate-limited to 1 call per 15 minutes per user (enforced server-side).

export type RefreshResult = {
  picks: AiPick[];
  rateLimited?: boolean;
  retryAfterMinutes?: number;
};

export async function refreshAiPicks(): Promise<RefreshResult> {
  const { data, error } = await supabase.functions.invoke("generate-ai-picks");

  if (error) {
    // 429 = rate limited
    if (error.message?.includes("429") || error.context?.status === 429) {
      const body = error.context ? await error.context.json().catch(() => ({})) : {};
      return { picks: [], rateLimited: true, retryAfterMinutes: body.retry_after ?? 15 };
    }
    throw new Error(error.message ?? "Failed to generate AI picks");
  }

  return { picks: data?.picks ?? [] };
}

export async function getCachedAiPicks(): Promise<AiPick[]> {
  const now = new Date().toISOString();
  const { data, error } = await supabase
    .from("ai_picks")
    .select("*")
    .gt("expires_at", now)
    .order("value_rating", { ascending: false })
    .order("created_at", { ascending: false })
    .limit(20);

  if (error) throw new Error(error.message);
  return data ?? [];
}
